"""Plugin implementation for Mistral Voxtral transcription through Hugging Face Transformers

Docs: https://cj-mills.github.io/cjm-transcription-plugin-voxtral-hfplugin.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/plugin.ipynb.

# %% auto #0
__all__ = ['VoxtralHFPluginConfig', 'VoxtralHFPlugin']

# %% ../nbs/plugin.ipynb #f2fbcf2b
import os
import sys
from uuid import uuid4
import logging
from pathlib import Path
from dataclasses import dataclass, field
from dataclasses import replace as dataclass_replace
from typing import Dict, Any, Optional, List, Union, Generator, ClassVar
import tempfile
import warnings
from threading import Thread

from fastcore.basics import patch

import torch

try:
    from transformers import VoxtralForConditionalGeneration, AutoProcessor
    from transformers import TextStreamer, TextIteratorStreamer
    VOXTRAL_AVAILABLE = True
except ImportError:
    VOXTRAL_AVAILABLE = False
    
from cjm_transcription_plugin_system.plugin_interface import TranscriptionPlugin
from cjm_transcription_plugin_system.core import TranscriptionResult
from cjm_transcription_plugin_system.storage import TranscriptionStorage
from cjm_plugin_system.utils.hashing import hash_file, hash_bytes, hash_dict_canonical
from .meta import get_plugin_metadata
from cjm_plugin_system.core.interface import RELOAD_TRIGGER, EnvVarSpec
from cjm_plugin_system.core.errors import (
    PluginInputError, PluginFatalError, PluginResourceError,
)
from cjm_plugin_system.utils.validation import (
    dict_to_config, config_to_dict, validate_config, dataclass_to_jsonschema,
    SCHEMA_TITLE, SCHEMA_DESC, SCHEMA_MIN, SCHEMA_MAX, SCHEMA_ENUM
)
from cjm_transcription_plugin_voxtral_hf.meta import (
    get_plugin_metadata
)
from cjm_torch_plugin_utils.memory import release_model
from cjm_torch_plugin_utils.oom import cuda_oom_to_plugin_resource_error
from cjm_hf_plugin_utils.cache_config import HFCacheConfig
from cjm_hf_plugin_utils.download import snapshot_download_with_progress
from cjm_hf_plugin_utils.loading import load_pretrained_with_oom

# %% ../nbs/plugin.ipynb #config-dataclass
@dataclass
class VoxtralHFPluginConfig(HFCacheConfig):
    """Configuration for Voxtral HF transcription plugin."""
    model_id:str = field(
        default="mistralai/Voxtral-Mini-3B-2507",
        metadata={
            SCHEMA_TITLE: "Model ID",
            RELOAD_TRIGGER: "model",  # CR-4: change triggers model reload
            SCHEMA_DESC: "Voxtral model to use. Mini is faster, Small is more accurate.",
            SCHEMA_ENUM: ["mistralai/Voxtral-Mini-3B-2507", "mistralai/Voxtral-Small-24B-2507"]
        }
    )
    device:str = field(
        default="auto",
        metadata={
            SCHEMA_TITLE: "Device",
            RELOAD_TRIGGER: "model",  # CR-4: change triggers model reload
            SCHEMA_DESC: "Device for inference (auto will use CUDA if available)",
            SCHEMA_ENUM: ["auto", "cpu", "cuda"]
        }
    )
    dtype:str = field(
        default="auto",
        metadata={
            SCHEMA_TITLE: "Data Type",
            RELOAD_TRIGGER: "model",  # CR-4: change triggers model reload
            SCHEMA_DESC: "Data type for model weights (auto will use bfloat16 on GPU, float32 on CPU)",
            SCHEMA_ENUM: ["auto", "bfloat16", "float16", "float32"]
        }
    )
    language:Optional[str] = field(
        default="en",
        metadata={
            SCHEMA_TITLE: "Language",
            SCHEMA_DESC: "Language code for transcription (e.g., 'en', 'es', 'fr')"
        }
    )
    max_new_tokens:int = field(
        default=25000,
        metadata={
            SCHEMA_TITLE: "Max New Tokens",
            SCHEMA_DESC: "Maximum number of tokens to generate",
            SCHEMA_MIN: 1,
            SCHEMA_MAX: 50000
        }
    )
    do_sample:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Do Sample",
            SCHEMA_DESC: "Whether to use sampling (true) or greedy decoding (False)"
        }
    )
    temperature:float = field(
        default=1.0,
        metadata={
            SCHEMA_TITLE: "Temperature",
            SCHEMA_DESC: "Temperature for sampling (only used when do_sample=true)",
            SCHEMA_MIN: 0.0,
            SCHEMA_MAX: 2.0
        }
    )
    top_p:float = field(
        default=0.95,
        metadata={
            SCHEMA_TITLE: "Top P",
            SCHEMA_DESC: "Top-p (nucleus) sampling parameter (only used when do_sample=true)",
            SCHEMA_MIN: 0.0,
            SCHEMA_MAX: 1.0
        }
    )
    compile_model:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Compile Model",
            SCHEMA_DESC: "Use torch.compile for potential speedup (requires PyTorch 2.0+)"
        }
    )
    load_in_8bit:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Load in 8-bit",
            RELOAD_TRIGGER: "model",  # CR-4: change triggers model reload
            SCHEMA_DESC: "Load model in 8-bit quantization (requires bitsandbytes)"
        }
    )
    load_in_4bit:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Load in 4-bit",
            RELOAD_TRIGGER: "model",  # CR-4: change triggers model reload
            SCHEMA_DESC: "Load model in 4-bit quantization (requires bitsandbytes)"
        }
    )


# %% ../nbs/plugin.ipynb #plugin-class
class VoxtralHFPlugin(TranscriptionPlugin):
    """Mistral Voxtral transcription plugin via Hugging Face Transformers."""

    config_class = VoxtralHFPluginConfig

    WORKER_ENV: ClassVar[List[EnvVarSpec]] = [
        EnvVarSpec(
            name="CUDA_VISIBLE_DEVICES",
            default="0",
            label="GPU Device",
            description="Which GPU index the worker uses.",
        ),
        EnvVarSpec(
            name="OMP_NUM_THREADS",
            default="4",
            label="OpenMP Threads",
            description="Thread cap for CPU-side ops.",
        ),
        EnvVarSpec(
            name="HF_HOME",
            default="${CJM_MODELS_DIR}/huggingface",
            label="HF Cache Directory",
            description="HuggingFace Hub cache root (templated to the substrate models dir).",
        ),
    ]

    def __init__(self):
        """Initialize the Voxtral HF plugin with default configuration."""
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")
        self.config: VoxtralHFPluginConfig = None
        self.model = None
        self.processor = None
        self.device = None
        self.dtype = None
        self.storage: Optional[TranscriptionStorage] = None

    @property
    def name(self) -> str: # Plugin name identifier
        """Get the plugin name identifier."""
        return get_plugin_metadata()["name"]

    @property
    def version(self) -> str: # Plugin version string
        """Get the plugin version string."""
        from cjm_transcription_plugin_voxtral_hf import __version__
        return __version__

    @property
    def supported_formats(self) -> List[str]: # List of supported audio formats
        """Get the list of supported audio file formats."""
        return ["wav", "mp3", "flac", "m4a", "ogg", "webm", "mp4", "avi", "mov"]

    def get_current_config(self) -> Dict[str, Any]: # Current configuration as dictionary
        """Return current configuration state."""
        if not self.config:
            return {}
        return config_to_dict(self.config)

    def get_config_schema(self) -> Dict[str, Any]: # JSON Schema for configuration
        """Return JSON Schema for UI generation."""
        return dataclass_to_jsonschema(VoxtralHFPluginConfig)

    @staticmethod
    def get_config_dataclass() -> VoxtralHFPluginConfig: # Configuration dataclass
        """Return dataclass describing the plugin's configuration options."""
        return VoxtralHFPluginConfig

    def initialize(
        self,
        config: Optional[Any] = None # Configuration dataclass, dict, or None
    ) -> None:
        """First-time setup. CR-4: the manual model/device/dtype/quantization
        diff-and-reload is replaced by declarative RELOAD_TRIGGER metadata; the
        substrate's reconfigure path fires _release_model then re-applies config."""
        self._apply_config(config)
        
        # Initialize standardized storage (one-time)
        db_path = get_plugin_metadata()["db_path"]
        self.storage = TranscriptionStorage(db_path)
        
        self.logger.info(f"Initialized Voxtral HF plugin with model '{self.config.model_id}' on device '{self.device}' with dtype '{self.dtype}'")

    def execute(
        self,
        audio: Union[str, Path], # Audio data or path to audio file to transcribe
        **kwargs # Additional arguments to override config
    ) -> TranscriptionResult: # Transcription result with text and metadata
        """Transcribe audio using Voxtral."""
        # Prepare audio file
        audio_path = self._prepare_audio(audio)
        temp_file_created = False  # caller provides a model-ready path; plugin never creates a temp file

        # Hash the audio file (content) for the cache key
        audio_hash = hash_file(audio_path)

        # Hash the effective config for cache keying. CR-15: config_hash derives from
        # self.config (the effective config); the per-call kwargs config-overrides below
        # are NOT reflected here — that override path predates the substrate overhaul and
        # is slated for removal (candidate CR-15 / project_execute_invocation_contract_gap).
        config_hash = hash_dict_canonical(config_to_dict(self.config))

        # 1. Cache check (content-correct: audio_path + audio_hash + config_hash), before
        #    loading the model so a pure cache hit skips the model load entirely.
        if not kwargs.get("force", False):
            cached = self.storage.get_cached(str(audio), audio_hash, config_hash)
            if cached:
                self.logger.info(f"Using cached transcription for {audio}")
                return TranscriptionResult(
                    text=cached.text,
                    confidence=None,
                    segments=cached.segments,
                    metadata=cached.metadata,
                )

        # 2. Cache miss — load the model and transcribe
        self._load_model()

        try:
            # Get config values, allowing kwargs overrides
            # CR-15: these per-call config-overrides bypass reconfigure/persistence/validation/
            # config_hash and are slated for removal; provenance kwargs (job_id/source_*_time) stay.
            model_id = kwargs.get("model_id", self.config.model_id)
            language = kwargs.get("language", self.config.language)
            max_new_tokens = kwargs.get("max_new_tokens", self.config.max_new_tokens)
            do_sample = kwargs.get("do_sample", self.config.do_sample)
            temperature = kwargs.get("temperature", self.config.temperature)
            top_p = kwargs.get("top_p", self.config.top_p)
            
            # Prepare inputs
            self.logger.info(f"Processing audio with Voxtral {model_id}")
            
            inputs = self.processor.apply_transcription_request(
                language=language or "en",
                audio=str(audio_path),
                model_id=model_id
            )
            inputs = inputs.to(self.device, dtype=self.dtype)
            
            # Generation kwargs
            generation_kwargs = {
                "max_new_tokens": max_new_tokens,
                "do_sample": do_sample,
            }
            
            # Add sampling parameters if sampling is enabled
            if do_sample:
                generation_kwargs["temperature"] = temperature
                generation_kwargs["top_p"] = top_p
            
            # Generate transcription. SG-47 Track B wraps the inference site so
            # CUDA OOM surfaces as PluginResourceError → CR-7 reactive-retry reloads.
            try:
                with torch.no_grad():
                    with warnings.catch_warnings():
                        warnings.simplefilter("ignore")
                        outputs = self.model.generate(
                            **inputs,
                            **generation_kwargs
                        )
            except torch.cuda.OutOfMemoryError as e:
                raise cuda_oom_to_plugin_resource_error(
                    e, label=f"Voxtral inference (model={self.config.model_id!r})",
                ) from e
            
            # Decode the output
            result_text = self.processor.batch_decode(
                outputs[:, inputs.input_ids.shape[1]:], 
                skip_special_tokens=True
            )[0]

            # Clean up tensors immediately
            del inputs
            del outputs
            
            # Clear GPU cache if using CUDA
            if self.device == "cuda" and torch.cuda.is_available():
                torch.cuda.empty_cache()

            # Capture provenance metadata passed via kwargs
            provenance_meta = {
                k: v for k, v in kwargs.items() 
                if k in ['source_start_time', 'source_end_time']
            }
            
            # Create transcription result
            transcription_result = TranscriptionResult(
                text=result_text.strip(),
                confidence=None,  # Voxtral doesn't provide confidence scores
                segments=None,  # Voxtral doesn't provide segments by default
                metadata={
                    "model": model_id,
                    **provenance_meta,
                    "language": language or "en",
                    "device": self.device,
                    "dtype": str(self.dtype),
                }
            )

            # Hash the transcription output
            text_hash = hash_bytes(transcription_result.text.encode())

            # Save to standardized storage (helper logs success/failure; never raises)
            job_id = kwargs.get("job_id", str(uuid4()))
            self.storage.save_with_logging(
                job_id=job_id,
                audio_path=str(audio),
                audio_hash=audio_hash,
                config_hash=config_hash,
                text=transcription_result.text,
                text_hash=text_hash,
                segments=transcription_result.segments,
                metadata=transcription_result.metadata,
                logger=self.logger,
            )
            
            self.logger.info(f"Transcription completed: {len(result_text.split())} words")
            return transcription_result
            
        finally:
            # Clean up temporary file if created
            if temp_file_created:
                try:
                    Path(audio_path).unlink()
                except Exception:
                    pass


# %% ../nbs/plugin.ipynb #m-apply-config
@patch
def _apply_config(
    self:VoxtralHFPlugin,
    config: Optional[Any] = None # Configuration dataclass, dict, or None
) -> None:
    """CR-4: apply config + derive config-dependent state (device, dtype). No
    heavy-resource work. Called by initialize (first-time) and the substrate's
    reconfigure delta path. Model release on a model_id/device/dtype/quantization
    change is handled declaratively via RELOAD_TRIGGER -> _release_model."""
    self.config = dict_to_config(VoxtralHFPluginConfig, config or {})

    # Resolve device
    if self.config.device == "auto":
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
    else:
        self.device = self.config.device

    # Resolve dtype
    if self.config.dtype == "auto":
        if self.device == "cuda":
            self.dtype = torch.bfloat16
        else:
            self.dtype = torch.float32
    else:
        dtype_map = {
            "bfloat16": torch.bfloat16,
            "float16": torch.float16,
            "float32": torch.float32
        }
        self.dtype = dtype_map[self.config.dtype]


# %% ../nbs/plugin.ipynb #m-release-model
@patch
def _release_model(self:VoxtralHFPlugin) -> None:
    """Unload the current model + processor and free GPU memory.

    Delegates to cjm-torch-plugin-utils' `release_model` (move-to-CPU / del / gc /
    empty_cache / synchronize) -- the single source of truth across torch GPU plugins."""
    if self.model is None and self.processor is None:
        return
    self.logger.info("Unloading Voxtral model for reconfiguration")
    release_model(self, ["model", "processor"], self.device or "cuda", logger=self.logger)


# %% ../nbs/plugin.ipynb #m-load-model
@patch
def _load_model(self:VoxtralHFPlugin) -> None:
    """Load the Voxtral model + processor (lazy).

    The heartbeat wraps BOTH the (potentially long, often quiet) snapshot download
    AND the silent from_pretrained build, so the substrate's prefetch stall detector
    always sees the (progress, message) tuple advance. snapshot_download_with_progress
    layers real per-file download % on top when the HF Hub tqdm callback fires.
    CUDA OOM on load surfaces as a typed PluginResourceError for CR-7 reactive retry."""
    if self.model is not None and self.processor is not None:
        return
    self.logger.info(f"Loading Voxtral model: {self.config.model_id}")

    # Built before the heartbeat block (instant). The snapshot below guarantees the
    # cache is populated, so the loads run local-only.
    model_kwargs = {
        "cache_dir": self.config.cache_dir,
        "revision": self.config.revision,
        "trust_remote_code": self.config.trust_remote_code,
        "local_files_only": True,
        "device_map": self.device,
    }
    if self.config.load_in_8bit:
        from transformers import BitsAndBytesConfig
        model_kwargs["quantization_config"] = BitsAndBytesConfig(load_in_8bit=True)
    elif self.config.load_in_4bit:
        from transformers import BitsAndBytesConfig
        model_kwargs["quantization_config"] = BitsAndBytesConfig(load_in_4bit=True)
    else:
        model_kwargs["dtype"] = self.dtype

    try:
        with self.heartbeat(f"loading Voxtral model {self.config.model_id}"):
            # Download (honors air-gap via local_files_only). The heartbeat is the
            # floor here; the tqdm hook adds real "downloading <file>" % when it fires.
            snapshot_download_with_progress(
                self.config.model_id,
                report_progress=self.report_progress,
                cache_dir=self.config.cache_dir,
                revision=self.config.revision,
                local_files_only=self.config.local_files_only,
            )
            self.processor = AutoProcessor.from_pretrained(
                self.config.model_id,
                cache_dir=self.config.cache_dir,
                revision=self.config.revision,
                trust_remote_code=self.config.trust_remote_code,
                local_files_only=True,
            )
            self.model = load_pretrained_with_oom(
                VoxtralForConditionalGeneration,
                self.config.model_id,
                label=f"loading Voxtral model {self.config.model_id!r}",
                **model_kwargs,
            )

        if self.config.compile_model and hasattr(torch, "compile"):
            self.model = torch.compile(self.model)
            self.logger.info("Model compiled with torch.compile")
        self.logger.info("Voxtral model loaded successfully")
    except PluginResourceError:
        raise  # already typed by load_pretrained_with_oom
    except torch.cuda.OutOfMemoryError as e:
        # Defensive: OOM outside the wrapped model load (processor / compile).
        raise cuda_oom_to_plugin_resource_error(
            e, label=f"loading Voxtral model {self.config.model_id!r}",
        ) from e
    except Exception as e:
        raise PluginFatalError(f"Failed to load Voxtral model: {e}") from e


# %% ../nbs/plugin.ipynb #m-prepare-audio
@patch
def _prepare_audio(
    self:VoxtralHFPlugin,
    audio: Union[str, Path] # Path to a decodable audio file
) -> str: # The audio file path
    """Validate the audio input and return it as a path string.

    The caller (orchestration / proxy) guarantees a model-ready audio file;
    in-memory preparation is no longer a plugin responsibility."""
    if isinstance(audio, (str, Path)):
        return str(audio)
    raise PluginInputError(  # SG-47: typed input-validation (multi-inherits ValueError)
        f"Unsupported audio input type: {type(audio)}; expected a file path (str or Path)",
        fields_invalid=["audio"],
    )


# %% ../nbs/plugin.ipynb #m-is-available
@patch
def is_available(self:VoxtralHFPlugin) -> bool: # True if Voxtral and its dependencies are available
    """Check if Voxtral is available."""
    return VOXTRAL_AVAILABLE


# %% ../nbs/plugin.ipynb #m-prefetch
@patch
def prefetch(self:VoxtralHFPlugin) -> None:
    """CR-4 (SG-19): eagerly load the model + processor so the first execute()
    doesn't pay the download/load cost. Idempotent via _load_model's None-guard."""
    self._load_model()


# %% ../nbs/plugin.ipynb #m-on-disable
@patch
def on_disable(self:VoxtralHFPlugin) -> None:
    """CR-2: release the GPU model + processor when the operator disables the
    plugin (the worker stays alive); lazy reload on the next execute."""
    self._release_model()


# %% ../nbs/plugin.ipynb #m-cleanup
@patch
def cleanup(self:VoxtralHFPlugin) -> None:
    """Release the model + processor (CR-4: delegates to `_release_model`)."""
    self._release_model()


# %% ../nbs/plugin.ipynb #4f195e29
@patch
def supports_streaming(
    self:VoxtralHFPlugin
) -> bool:  # True if streaming is supported
    """Check if this plugin supports streaming transcription."""
    return True

@patch
def execute_stream(
    self:VoxtralHFPlugin,
    audio: Union[str, Path],  # Audio data or path to audio file
    **kwargs  # Additional plugin-specific parameters
) -> Generator[str, None, TranscriptionResult]:  # Yields text chunks, returns final result
    """Stream transcription results chunk by chunk."""
    # Load model if not already loaded
    self._load_model()
    
    # Prepare audio file
    audio_path = self._prepare_audio(audio)
    temp_file_created = False  # caller provides a model-ready path; plugin never creates a temp file
    
    try:
        # Get config values, allowing kwargs overrides
        model_id = kwargs.get("model_id", self.config.model_id)
        language = kwargs.get("language", self.config.language)
        max_new_tokens = kwargs.get("max_new_tokens", self.config.max_new_tokens)
        do_sample = kwargs.get("do_sample", self.config.do_sample)
        temperature = kwargs.get("temperature", self.config.temperature)
        top_p = kwargs.get("top_p", self.config.top_p)
        
        # Prepare inputs
        self.logger.info(f"Streaming transcription with Voxtral {model_id}")
        
        inputs = self.processor.apply_transcription_request(
            language=language or "en",
            audio=str(audio_path),
            model_id=model_id
        )
        inputs = inputs.to(self.device, dtype=self.dtype)
        
        # Create streamer
        from transformers import TextIteratorStreamer
        streamer = TextIteratorStreamer(
            self.processor.tokenizer, 
            skip_prompt=True, 
            skip_special_tokens=True
        )
        
        # Generation kwargs
        generation_kwargs = {
            **inputs,
            "max_new_tokens": max_new_tokens,
            "do_sample": do_sample,
            "streamer": streamer,
        }
        
        # Add sampling parameters if sampling is enabled
        if do_sample:
            generation_kwargs["temperature"] = temperature
            generation_kwargs["top_p"] = top_p
        
        # Start generation in a separate thread with torch.no_grad().
        # SG-47 Track B follow-up: thread target wraps the generate() call so
        # CUDA OOMs (and other exceptions) raised inside the thread propagate
        # back to the generator caller as typed PluginResourceError. The mutable
        # `generation_exception` list is the cross-thread propagation channel
        # — single-element capture is sufficient because we only re-raise once.
        generation_exception: List[BaseException] = []

        def generate_with_no_grad():
            try:
                with torch.no_grad():
                    self.model.generate(**generation_kwargs)
            except BaseException as e:
                # Capture for cross-thread propagation; re-raise so the thread
                # still terminates normally and HuggingFace's TextIteratorStreamer
                # gets its end-signal via the generate() finally block (the streamer
                # signals StopIteration to the consuming for-loop on end).
                generation_exception.append(e)
                raise

        thread = Thread(target=generate_with_no_grad)
        thread.start()

        # Collect generated text. If the thread crashes, HF's streamer signals
        # end (StopIteration) when generate's finally fires; the for-loop
        # terminates without yielding further chunks, and the post-iteration
        # exception check below re-raises the captured exception.
        generated_text = ""
        for text_chunk in streamer:
            generated_text += text_chunk
            yield text_chunk

        # Wait for generation to complete (bounded — generation should be done
        # by the time the streamer's iteration ended; this is mostly to flush
        # the captured exception state).
        thread.join(timeout=30.0)

        # SG-47 Track B follow-up: re-raise any thread-captured exception with
        # typed classification. CUDA OOMs map to PluginResourceError + populated
        # ResourceShortfall so CR-7's reactive-retry path can reload + retry.
        if generation_exception:
            exc = generation_exception[0]
            if isinstance(exc, torch.cuda.OutOfMemoryError):
                raise cuda_oom_to_plugin_resource_error(
                    exc, label=f"Voxtral streaming inference (model={model_id!r})",
                ) from exc
            # Non-OOM thread exception: re-raise as-is so the substrate's default
            # classify_exception() MRO walk classifies it via CR-5.
            raise exc

        # Clean up tensors immediately
        del inputs
        
        # Clear GPU cache if using CUDA
        if self.device == "cuda" and torch.cuda.is_available():
            torch.cuda.empty_cache()
        
        # Return final result
        return TranscriptionResult(
            text=generated_text.strip(),
            confidence=None,
            segments=None,
            metadata={
                "model": model_id,
                "language": language or "en",
                "device": self.device,
                "dtype": str(self.dtype),
                "streaming": True,
            }
        )
        
    finally:
        # Clean up temporary file if created
        if temp_file_created:
            try:
                Path(audio_path).unlink()
            except Exception:
                pass
